---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify(classify)
	intake(intake)
	advisor(advisor)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify;
	advisor -.-> __end__;
	advisor -.-> tools;
	classify -.-> advisor;
	classify -.-> intake;
	intake -.-> __end__;
	intake -.-> tools;
	tools -.-> advisor;
	tools -.-> intake;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
